### ISSUE TITLE
Add in 2 new Twilek heads with hoods 

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_Haks#14]
https://github.com/zunath/SWLOR_NWN/files/3025183/headsnakesinhoods.zip

**Comment by not-myself** [comment]
heads need more detail/shading  for more realistic look. on hold for now

**Comment by Xisifer** [comment]
These assets have been added with Head Pack 3: https://github.com/zunath/SWLOR_NWN/issues/1159
