### ISSUE TITLE
Chest piece fixes

### ISSUE THREAD

**Issue by acidchalk** [zunath/SWLOR_Haks#32]
So i started this a long time ago and i'm sure i may have missed one or two but this pack should make it so all the chest pieces fit all races and genders and should have inventory icons. I think i ended up not making inventory icons for the robot pieces since those probably won't get used on suits of armor.

should just be able to overwrite. Also, if you wanted to save some space you could delete all of the IPF_ plt files. Those are the inventory icons for the female pieces and quite frankly i never thought armor icons needed titts but that's up to ya'll

https://www.dropbox.com/s/k588h8314801t93/chests.zip?dl=0

**Comment by Cavcode** [comment]
you can close this, including it in my PR
