### ISSUE TITLE
Armor pieces missing on non human based races

### ISSUE THREAD

**Issue by acidchalk** [zunath/SWLOR_Haks#39]
so instead of trying to figure out which ones were missing i took all of the human male and female pieces and ran them through armory. Just overwrite everything that was already there. This includes all of swlors parts for half orc elf and dwarf phenotypes

https://www.dropbox.com/s/p98zd8u6ywpgiii/body%20parts.rar?dl=0

**Comment by zunath** [comment]
We're not sure it's safe to import this as-is given how long it's taken me to get back to the ticket. It's possible the models in this package will overwrite different assets. If this becomes a problem, we can review this package again in the future.
