### ISSUE TITLE
Add new jedi robes for humans,elves and orcs 

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_Haks#4]
Original post: https://github.com/zunath/SWLOR_NWN/issues/847

Hello here are some new robes, this version overwrites the current trechcoat model so you might want to renumber it unless you would want to replace it.

https://github.com/zunath/SWLOR_NWN/files/2981855/overrideSW.zip

**Comment by not-myself** [comment]
I'm looking at this one

**Comment by not-myself** [comment]
This robe is already in the game as #236. I think you can close this
