### ISSUE TITLE
Draygoth's SW Content

### ISSUE THREAD

**Issue by zunath** [zunath/SWLOR_Haks#6]
https://cdn.discordapp.com/attachments/518972781665320960/520999751747895337/Starwars_stuff.zip

**Comment by not-myself** [comment]
We've got a lot of content already, but I packed it into a hak in case anybody wants to poke at it and see if theres anything we'd want out of it
[SWLOR_Draygoth.zip](https://github.com/zunath/SWLOR_Haks/files/3445131/SWLOR_Draygoth.zip)
