### ISSUE TITLE
TIK Hutlar maps + Narr Shaddaa DM event map.

### ISSUE THREAD

**Issue by TheTik-keeper** [zunath/SWLOR_Haks#69]
[TIK Swlor Maps (No scripting or NPCs).zip](https://github.com/zunath/SWLOR_Haks/files/7403466/TIK.Swlor.Maps.No.scripting.or.NPCs.zip)

These are my maps to expand hutlar. Includes Qion Tundra as I made a mild edit to it so that it leads into the Valley map, but the specific placement isn't important if using that version would cause issues.

In addition, there's no scripting or NPCs on any of these maps, that still needs to be done. The 'Abandoned Outpost' and 'Cloning Test Site' areas need monsters and loot spawning scripts, as it's meant to be a dungeon. (Maybe a quest too?). Message me on discord for the ideas I had about it.

**Comment by zunath** [comment]
I've imported these files to the revamp module. I won't be importing to the legacy module as it will require doing the same work twice (spawns, loot, etc.). Anyone else is welcome to do the work if they can't wait for the revamp to launch.
